### ISSUE TITLE
no more wheel  on pypi ?

### ISSUE THREAD

**Issue by stonebig** [blaze/distributed#81]
There was a wheel for 1.7.1, but there is no more for 1.7.3.

It would be nice to have it back, unless it's a problem.

**Comment by mrocklin** [comment]
I ran into problems with universal wheels because my `install_requires` field in setup.py changes based on the version.  I created the universal wheel in Python 3 and the Python 2 wheel didn't cause the installation of some dependencies (notably `futures`).  Do you have suggestions on how to resolve this?

Generally this project is still pretty experimental.  I issue releases on a roughly weekly basis and they are, as far as I can tell, only used by a handful of beta testers.  I'll endeavor to remember to publish wheels but it's just not a high priority at the moment.

**Comment by stonebig** [comment]
I don't think you can do an universal wheel with that sort of variation.

A possible suggestion would be to stop keeping Python2.7 compatibility for new packages like this one.

**Comment by mrocklin** [comment]
I appreciate the suggestion, but I'm not yet willing to sacrifice the broad user pool.

**Comment by stonebig** [comment]
another suggestion would be to have pip package functionnalities improved, but it's a much more complex suggestion.

**Comment by mrocklin** [comment]
Yeah, both are out of scope for me.  I plan to continue with source packages for a while until I decide to release this to a wider audience.

What is your involvement here again?  I recall that you manage packages of some sort, yes?

**Comment by stonebig** [comment]
yes, on Windows user space, where everything is more complex, except using wheels. I'll wait, sorry for the disturbance.
